# docker-compose for dev

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

  question:
    build:
      context: ./backend/question-service
      dockerfile: Dockerfile.dev
    ports:
      - "2000:2000"
    develop:
      watch:
        - action: sync
          path: ./backend/question-service
          target: /app

  user:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/user-service/.env
    ports:
      - "3001:3001"
