services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    # depends_on:
    #   - 
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app