# docker-compose for dev

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    # depends_on:
    #   - 
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

  question:
    build:
      context: ./backend/question-service
      dockerfile: Dockerfile.dev
    # depends_on:
    #   - 
    ports:
      - "2000:2000"
    develop:
      watch:
        - action: sync
          path: ./backend/question-service
          target: /app
